service: abalone
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  iamRoleStatements:
    # Access the published endpoint for abalone age prediction.
    - Effect: "Allow"
      Action:
        - "sagemaker:InvokeEndpoint"
      Resource:
        - "arn:aws:sagemaker:us-east-1:679892560156:*"

functions:
  hello:
    handler: src.handler.hello

  testEndpoint:
    handler: src.handler.test_endpoint

  createEstimator:
    handler: src.handler.create_estimator
    layers:
      - arn:aws:lambda:us-east-1:679892560156:layer:sagemaker-pandas:1
      - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x:2
